name: Build and Push Anna Bot

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Substituir usuário para minúsculo
        id: string
        run: |
          # Esse comando pega o nome do seu repositório completo (Filnr/anna-bot) e transforma tudo em minúsculo
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lower=${REPO_LOWER}" >> $GITHUB_OUTPUT

      - name: Buildar e Enviar Imagem Docker
        uses: docker/build-push-action@v6  # Atualizado para v6 para evitar avisos de depreciação
        with:
          context: .
          push: true
          # Aqui usamos o resultado do passo anterior com letras estritamente minúsculas
          tags: ghcr.io/${{ steps.string.outputs.repo_lower }}:latest